// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcCvtpSzcEjXZtUHi4z46KCLLvxCE8x0',
    appId: '1:668082011772:web:81ad482d4d8aa3a19193f9',
    messagingSenderId: '668082011772',
    projectId: 'mvvmshop-21b38',
    authDomain: 'mvvmshop-21b38.firebaseapp.com',
    storageBucket: 'mvvmshop-21b38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX1YBWquc1lZNtP7uJeXqMjO_ueTxnei0',
    appId: '1:668082011772:android:6f32631473ba1a779193f9',
    messagingSenderId: '668082011772',
    projectId: 'mvvmshop-21b38',
    storageBucket: 'mvvmshop-21b38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo0J-AB75hebYNkGP-BVYm5QSkFMUToRg',
    appId: '1:668082011772:ios:ad31e9722638450a9193f9',
    messagingSenderId: '668082011772',
    projectId: 'mvvmshop-21b38',
    storageBucket: 'mvvmshop-21b38.appspot.com',
    iosBundleId: 'com.example.mvvmShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo0J-AB75hebYNkGP-BVYm5QSkFMUToRg',
    appId: '1:668082011772:ios:ad31e9722638450a9193f9',
    messagingSenderId: '668082011772',
    projectId: 'mvvmshop-21b38',
    storageBucket: 'mvvmshop-21b38.appspot.com',
    iosBundleId: 'com.example.mvvmShop',
  );
}
